layout_spectrum: 0.8199717
color:
  saturation: 0.4987469
  lightness: 0.4974937
  brandStrength: 0.4761905
  brandColors:
    - '#4C7790'
    - '#655C4B'
    - '#382F03'
    - '#D9CECE'
    - '#05040B'
  rhythmicContrast: 0.5006266
typography_spectrum: 0.3104141
name: Phillip Berry
